#!/bin/sh
set -eu

CMD="$1"
shift

DIR=""
i="0"
ii="$#"
while test "$i" -lt "$ii"; do
  OPT="$1"
  shift
  case "$OPT" in
    "--")
      if test -z "$DIR"; then
        i="$((i+1))"
        OPT="$1"
        shift
        DIR="$OPT"
      else
        set -- "$@" "$OPT"
      fi;;
    "-"*)
      set -- "$@" "$OPT";;
    *)
      if test -z "$DIR"; then
        DIR="$OPT"
      else
        set -- "$@" "$OPT"
      fi;;
  esac
  i="$((i+1))"
done

DIR="$(readlink -f -- "$DIR")"
INSTANCE="$(systemd-escape -p "$DIR")"

if test "$CMD" = "docker"; then
  cd "$DIR"
  COMPOSE_PROJECT_NAME="$INSTANCE" exec docker-compose "$@"
elif test "$CMD" = "journalctl"; then
  exec journalctl -u compose@"$INSTANCE" "$@"
else
  exec systemctl "$CMD" compose@"$INSTANCE" "$@"
fi
