#!/bin/sh
set -eu

CMD="$1"
shift
DIR="$(readlink -f -- "$1")"
shift

INSTANCE="$(systemd-escape -p "$DIR")"

if test "$CMD" = "docker"; then
  cd "$DIR"
  COMPOSE_PROJECT_NAME="$INSTANCE" exec docker-compose "$@"
elif test "$CMD" = "journalctl"; then
  exec journalctl -u compose@"$INSTANCE" "$@"
else
  exec systemctl "$CMD" compose@"$INSTANCE" "$@"
fi
